### ISSUE TITLE
typora报错

### ISSUE THREAD

**Issue by xincanzhe** [thep0y/timg#2]
图片已经上传到github上，但是没有返回给typora的数据，或者说有可能我的github令牌权限设置错误，可否告知，github令牌需要哪些权限？
![](https://ftp.bmp.ovh/imgs/2021/03/9ff41df4d018489e.png)

**Comment by thep0y** [comment]
是代码的问题，没有打印上传成功后的链接，现在已经添加了打印，可以使用了，需要更新一下timg：
```shell
pip install typora-upload-image --upgrade -i https://pypi.org/simple
```
